name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}"
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: "${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pre-commit-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Security audit
        run: pip-audit -r requirements.txt -r requirements-dev.txt
      - name: Install CycloneDX Python SBOM Tool
        run: |
          python -m pip install cyclonedx-bom
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Generate SBOM
        run: cyclonedx-py requirements -i requirements.txt -o sbom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        if: ${{ env.SNYK_TOKEN != '' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        run: snyk test
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --apiKey "$RAILWAY_TOKEN"
      - name: Lint
        run: pre-commit run --all-files
      - name: Test
        run: |
          python -m pytest --cov=. --cov-report=term-missing:skip-covered \
            --cov-report=xml --cov-fail-under=90
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
      - name: Capture Railway logs
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          mkdir -p logs
          railway logs --follow > logs/latest_railway.log
      - uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: logs/latest_railway.log
