name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint
        run: pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Test
        run: PYTHONPATH=src python -m pytest --cov=src/wcr_data_api -q --cov-report=xml
      - name: Security Audit
        run: pip-audit -r requirements.txt > audit.txt
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
      - uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: audit.txt
