name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Security audit
        run: pip-audit -r requirements.txt -r requirements-dev.txt
      - name: Bandit security scan
        run: bandit -r src -q
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Lint
        run: pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Test
        run: python -m pytest --cov=src/wcr_api --cov=main -q --cov-report=xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
