name: Railway Logs

on:
  workflow_dispatch:

jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Login to Railway
        run: railway login --token "$RAILWAY_TOKEN"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Stream production logs
        run: |
          mkdir -p logs
          railway logs --environment production --service bot --detach > logs/latest_railway.log || true
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: railway-latest-log
          path: logs/latest_railway.log
