name: Railway Logs

on:
  workflow_dispatch:

jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Login to Railway
        run: railway login --apiKey "$RAILWAY_TOKEN"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Stream railway logs
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          mkdir -p logs
          railway logs --follow > logs/latest_railway.log
      - uses: actions/upload-artifact@v4
        with:
          name: railway-latest-log
          path: logs/latest_railway.log
