name: Railway Logs

on:
  workflow_dispatch:

jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Stream production logs
        run: |
          mkdir -p logs
          npx railway logs --service $RAILWAY_SERVICE --project $RAILWAY_PROJECT --env production --json > logs/latest_railway.log
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT }}
      - uses: actions/upload-artifact@v4
        with:
          name: railway-latest-log
          path: logs/latest_railway.log
